### ISSUE TITLE
Some concerns about this project

### ISSUE THREAD

**Issue by AliceAstro** [aforensics/HiddenVM#24]
I have some reservations regarding the state of this project. It does seem to exist for a good purpose but there has been no changes to the repo especially regarding the continued usage of vbox instead of virt-manager and the delayed move to python because of a supposed "lack of time" despite the latter being announced over 18 months ago. The same excuse has been used for the former despite the former change being the easiest to make by switching out vbox for virt-manager requiring the least minimum changes to the codebase compared to the latter.

Either the project author has been compromised by a rogue state actor or has been working with one all along. This attitude is very similar to the flawed modus operandi of security through obscurity atitude of the vbox developers in regards to patching the spectre and meltdown vulnerabilities. I know the project is open source that being said I have extracted the AppImage and viewed through the code there doesn't seem to be any malicious component to the codebase other than the ones already existing in VirtualBox. It is safe to say that the project author's main concerns is not security. It is advised that users of this project not continue using this project for their own safety and wait for another author to publish a project with a hypervisor that uses KVM.

**Comment by aforensics** [comment]
I really hoped to get going with the big Python port, but I'm involved with other things, I'm just too busy. I'm very sorry. I'm spending more time than I should just to make this long reply.

It's healthy to be paranoid. I advise you to be paranoid. (But don't use nothing, otherwise you're guaranteed not safe at all.) It is great you have checked the code. That's all you can do in this case. Whether you choose to still not use it, based on things looking weird, I can't do anything about that. I respect your opinion that I may look like a bad actor to you. I think your assessment is a little harsh though.

This could help convince you that no rogue state actors are involved with this project: if someone makes a KVM equivalent of this tool with no significantly less functionality and ease of use, and they don't appear to be a bad actor themselves, and they look dedicated to maintaining its functionality long-term like I loyally do with HiddenVM, then I will gladly advise people to use that project and officially close down this one (if I stop maintaining it). I will myself use that other tool.

However, now I'd want them to also offer a VirtualBox variant. Over the last year of using HiddenVM every day, I've learned that VBox has many features for advanced users that I don't think KVM offers (at least in accessible GUI), and VirtualBox can be locked down very strongly (even if there were a bad zero-day). HiddenVM should not be the only tool you use if you're really serious. Use Firejail, OpenSnitch, AppArmor, etc. If a replacement tool were KVM-only, it would have to have a major GUI interface to do most of what VBox does for regular users. And remember that tools like KVM can just easily have vulnerabilities as VirtualBox. It's not a magic panacea.

Until then, I obviously consider it safe for me to use HVM, and I use it daily. In two and a half years not one HVM 'backdoor' has been reported. No core functionality has fallen apart. (I will not let that happen.) There are much worse states of projects out there, yet many people use them, since nothing else better exists. Is there anything currently better than this? If so, please link it. Otherwise, why wait indefinitely while not gaining the benefits HVM provides? That makes little sense, but I really do understand your feelings of paranoia and trust issues. No matter the transparency of the code, maybe another solution feels safer for you.

I am sorry that the ambitions for this project have gone dormant for now. This is currently in 'maintenance mode'. Welcome to open-source. It's frustrating and imperfect. Projects like this can go for years before picking up significant development activity once more. Safety-wise, HVM almost fully relies on the security of upstream tools - Tails, Debian, Linux kernel, etc. If 'sudo' has a discovered vulnerability, it's patched by upgrading Tails, and HiddenVM remains secure to use.

I have a plan, if no one creates a well-maintained HVM equivalent, to eventually bring in other coders with time to actually work on it and give it the life it deserves. It takes money, I plan to add donation links. I just have no ETA on that. Stay safe.

Ticket closed.
