### ISSUE TITLE
Could it be possible to extend HiddenVM among other more mainstream distros, like Debian/Ubuntu or CentOS/Fedora?

### ISSUE THREAD

**Issue by q2dg** [aforensics/HiddenVM#3]
Would it be feasible/desirable?
Thanks!

**Comment by animik** [comment]
- The whole point of HiddenVM is to avoid a forensic trace on your hard drive of your persistent VMs. Therefore the whole point is to use Tails.

- HVM is also fully customized _for_ Tails. A lot of hard work has been done to make it a one-click solution for the user (it was not trivial to code up) and we will need to continue to adapt to new Tails releases and changes in the background that users don't know about. Making HVM work smoothly on other distros would require a fork for each new distro. HVM might already work on a pure Debian host OS (or even others based on it) but we haven't tried it.

I'd say you're looking at this from the wrong angle. If you love and want to use Debian/Ubuntu or CentOS/Fedora, use them as VMs inside Tails via HiddenVM! :) Tails as your base OS is what allows this new type of privacy.

Besides there's no point or extra benefit to using HiddenVM on non-amnesic distros. Just install VirtualBox as a persistent application like you normally do. With Fedora as a host OS, because it's not amnesic like Tails it's already game over, so in that case it means you wouldn't be interested in HiddenVM.

I'll let aforensics comment further, and close. After that happens please continue your thoughts at our [subreddit](reddit.com/r/HiddenVM/).

**Comment by q2dg** [comment]
Ok, thanks a lot for your clear explanation. Don't mind, I'll close this issue right now. Thanks!

**Comment by aforensics** [comment]
HiddenVM cannot run outside of Tails because the code is very specific to Tails. It most cases it can only be run on a specific version of Tails.
