### ISSUE TITLE
Using Tor Bridges

### ISSUE THREAD

**Issue by HiddenVMUser** [aforensics/HiddenVM#30]
Hi,

Is it OK to use Tor Project provided transport obfs4 bridges when connecting to Tor in Tails to reduce the chance of your ISP detecting you are using Tor? Will these Tor Bridges be used when you connect to Tor in Whonix  Gateway and Workstation? Or are these bridges going to cause security problems. Or should they be used in the tor anonymizer connection wizard within Virtual Box - Gateway? Or should no bridges be used in the Hidden VM system?

Thanks

**Comment by Random-Anon69** [comment]
Hello @HiddenVMUser,
The Tor settings you used on Tails Tor connection startup have absolutly no impact on HiddenVM, because HiddenVM is setup to connect with your clearnet connection, specially to avoid Tor over Tor connection issue with Whonix. The only impact that setting with have is when you Open Tor Browser directly on Tails or while installing HiddenVM, since the terminal is connected trough the Tor on Tails.

If you want your Whonix Workstation to used Tor Bridge, you have to configure your Whonix Gateway to do so. You can change the Whonix Gateway Tor connection using the "Tor Control panel" app, available on the menu in System tab.

**Comment by HiddenVMUser** [comment]
Thanks for clarifying that for me.

**Comment by aforensics** [comment]
Thank you for helping another user.
