### ISSUE TITLE
Timing attacks

### ISSUE THREAD

**Issue by llamabyte** [aforensics/HiddenVM#35]
Doesn't HVM having access to clearnet along side tor make it vulnerable to timing attacks ?

**Comment by aforensics** [comment]
No, it's fine (or rather, no worse than any other way of using Tor whether Tails or Whonix) because network functions over clearnet (VM activity) are not what's done by the core HiddenVM installation, which is only on Tor. (As for VirtualBox itself, an open-source app, clearnet DNS is blocked by default in Tails so its extra-VM functions like in-app VirtualBox updating is blocked by default.) So, everything is compartmentalized in a way that no extra risk is caused by HiddenVM.
