### ISSUE TITLE
Is it safe if the flash drive is pulled?

### ISSUE THREAD

**Issue by SourCandy80** [aforensics/HiddenVM#36]
Was just curious if pulling the flash drive while powered on would have any adverse effects, or if everything would still be encrypted and 100% safe?

Thanks in advance!

**Comment by aforensics** [comment]
If you use correctly set up deniable encryption, as far as the privacy community knows, it only gets down to information stored in live (or video) memory / RAM for a short time. (Hard drive remains rock solid, impenetrable.) Just try to not have computer seized by adversary less than one minute (or possibly a little longer) after you pull stick out, otherwise they could place in a freezer. (Tails documentation I think talks about this attack.)

Or if you mean in terms of data integrity, in my experience, it's very robust. But if you were doing work in a VM while pulling stick out, data corruption may exist in a Vbox VDI etc., so always do regular encrypted backups of your full data.

Stay safe!
