### ISSUE TITLE
Error on slow computer due to sudo timing out

### ISSUE THREAD

**Issue by basnappl** [aforensics/HiddenVM#5]
Installation halted and log said:

`[HiddenVM] [launch-log-progress.sh] Reset sudo timeout policy`

I'm guessing it was just taking long than expected.  Is there someway to increase the sudo timeout period or at least check and re-request root if necessary?

Edit:  Upon re-executing the appimage, the process succeeded

**Comment by aforensics** [comment]
That log line occurs at the very end of a HiddenVM installation, as a cleanup step to restore the sudo timeout policy to its original form. It happens whether an error occurs or not. So that's not an error. The actual error you experienced should be present in the log file prior to that line.

If the installation fails with an error that can't be addressed by the user, please attach the full log for us to investigate.

Thank you, your feedback is appreciated.
